@echo off

echo.
echo                       SAxVCxLC 0.8.5 Installation 
echo.
echo Enter the full path to the GTA SA root folder WITHOUT a backslash at the end.
echo You can drag ^& drop^ the folder here from explorer, then click on this command window again.
:SArootLabel
SET /P GTASAroot=GTASAroot=
if not exist %GTASAroot%\GTA_SA.exe (
	echo.
	echo %GTASAroot%\GTA_SA.exe DOES NOT EXIST. The path is probably wrong. Try again.
	echo.
	goto :SArootLabel
)

REM echo The path is: %GTASAroot%
echo   Added the path to InstallSettings.bat	

echo REM This file was generated by Install.bat and is used by Install.bat. You can edit or delete this file. Author Goodidea82 > InstallSettings.bat
echo SET GTASAroot=%GTASAroot% >> InstallSettings.bat 

echo ----------------------
REM --------------------------------------

echo Installation variants:
echo   1. Standard version with minor extras
echo   2. Raw/basic version without any extras 
echo   3. MTA version (Not available yet)
echo   4. Install additional mods (SAxVCxLC must have been installed already!)
choice  /C 1234 /M "Select an installation variant."
SET Variant=%ERRORLEVEL%
echo SET Variant=%Variant% >> InstallSettings.bat 
echo   Added variant decision to InstallSettings.bat

echo ----------------------
REM --------------------------------------

:repeatML
choice /M "Use ModLoader"
SET useModLoader=%ERRORLEVEL%
echo SET useModLoader=%useModLoader% >> InstallSettings.bat 
echo   Added ModLoader decision to InstallSettings.bat
if not exist %GTASAroot%\modloader.asi (
	echo.
	echo %GTASAroot%\modloader.asi DOES NOT EXIST. You must install ModLoader first, then try again.
	echo See http://www.gtagarage.com/mods/show.php?id=25377
	REM May be we should provide ModLoader in the otherMods folder?
	echo.
	goto :repeatML
)

REM --------------------------------------
REM S= Use this option to copy directories, subdirectories, and the files contained within them, in addition to the files in the root of source. Empty folders will not be recreated.
REM I= Use this option to show a list of the files and folders to copied... but no copying is actually done. The /l option is useful if you're building a complicated xcopy command with several options and you'd like to see how it would function hypothetically.
REM Y= Use this option to stop the xcopy command from prompting you about overwriting files from source that already exist in destination.
REM D=  Use the xcopy command with /d option and a specific date, in MM-DD-YYYY format, to copy files changed on or after that date. You can also use this option without specifying a specific date to copy only those files in source that are newer than the same files that already exist in destination. This is helpful when using the xcopy command to perform regular file backups.
REM Do not use empty options
set xcpyOpt=/Y

:skipDOpt
REM --------------------------------------

REM Start Installation

if "%Variant%"=="1" (call toolsForInstallation\Standard.bat %xcpyOpt% %useModLoader% "%GTASAroot%")
if "%Variant%"=="2" (call toolsForInstallation\Base.bat %xcpyOpt% %useModLoader% "%GTASAroot%")
if "%Variant%"=="3" (call toolsForInstallation\MTA.bat %xcpyOpt% %useModLoader% "%GTASAroot%")
if "%Variant%"=="4" (
	call toolsForInstallation\MTA.bat %xcpyOpt% %useModLoader% "%GTASAroot%"
	exit
)

REM -------------------------------------
echo -------------------------------------
REM update models\gta3.img
REM The script file gta3_img_changes.txt is located in SAxVCxLC_source\basic\models. It should have been copied to GTASAroot by the scripts above. 
goto :finish

echo update models\gta3.img
set toolsForInstDir=%CD%\toolsForInstallation
set thisDir=%CD%
cd "%GTASAroot%\models"
"%toolsForInstDir%\fastman92ImgConsole32.exe" -script gta3_img_changes.txt
cd "%thisDir%"

:finish
REM -----------------------------------------------
echo -------------------------------------------------------------
SET /P a=Finished installation of SAxVCxLC. Press a key to quit...
EXIT

REM --------------------------------------
:Trim
SetLocal EnableDelayedExpansion
set Params=%*
for /f "tokens=1*" %%a in ("!Params!") do EndLocal & set %1=%%b
exit /b
