REM This file was generated by Install.bat and is used by Install.bat. You can edit or delete this file. Author Goodidea82 
SET GTASAroot=C:\tmp\GTA_SA_test  
SET Variant=1  
SET useModLoader=2  
